{{- if .Values.credentials }}
{{- if gt (len .Values.credentials) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keel.fullname" . }}-credentials
  labels:
    {{- include "keel.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  {{- range $key, $value := .Values.credentials }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- end }}
