{{- if .Values.cluster.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "keel.fullname" . }}-cluster
  labels:
    {{- include "keel.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.cluster.port }}
      targetPort: cluster
      protocol: TCP
      name: cluster
  selector:
    {{- include "keel.selectorLabels" . | nindent 4 }}
{{- end }}
