/**
 * @file test_proxy_ssv_e2e.c
 * @brief End-to-end proxy tests for PostgreSQL semantic state virtualization.
 *
 * This suite uses a single worker and a single backend connection so stmt-set
 * mismatches deterministically force the DISCARD ALL + replay path.
 */

#include "test_utils.h"
#include "test_integration.h"

#include <errno.h>
#include <signal.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/wait.h>
#include <unistd.h>
#include <limits.h>

#define KEEL_PROXY_PORT 16433
#define KEEL_CONFIG_FILE "keel_ssv_test.ini"

#define TEST_USER "test"
#define TEST_PASSWORD "test"
#define TEST_DATABASE "postgres"

#define PROXY_START_TIMEOUT_SEC 10
#define PROXY_STOP_TIMEOUT_SEC 5

#define KEEL_RUNTIME_CONFIG_FILE "/tmp/keel_ssv_test_runtime.ini"

static pid_t g_proxy_pid = 0;
static bool g_cluster_started_by_test = false;
static bool g_skip_tests = false;

/**
 * @brief Locate the keel proxy binary for E2E testing.
 *
 * Searches a set of candidate build-output paths, then falls back to
 * `which keel`.  Returns NULL if no executable is found.
 *
 * @return Absolute path to the keel binary, or NULL.
 */
static const char* find_proxy_binary(void)
{
    static char path[PATH_MAX];
    const char* candidates[] = {
        "../src/main/keel",
        "../../build/src/main/keel",
        "./keel",
        NULL
    };

    for (int i = 0; candidates[i]; i++) {
        if (access(candidates[i], X_OK) == 0) {
            if (realpath(candidates[i], path))
                return path;
            return candidates[i];
        }
    }

    FILE* fp = popen("which keel 2>/dev/null", "r");
    if (fp) {
        if (fgets(path, sizeof(path), fp)) {
            path[strcspn(path, "\n")] = '\0';
            pclose(fp);
            if (access(path, X_OK) == 0)
                return path;
        }
        pclose(fp);
    }

    return NULL;
}

/**
 * @brief Generate a minimal runtime INI config for the SSV E2E tests.
 *
 * Writes a single-worker, single-backend configuration to
 * KEEL_RUNTIME_CONFIG_FILE with transaction pool mode and
 * PS-mode=tracking.  The single-backend constraint is critical:
 * it forces every backend reassignment through the DISCARD ALL +
 * replay path, making SSV correctness deterministic.
 *
 * @param out_path      [out] Receives the config file path.
 * @param out_path_len  Capacity of @p out_path.
 * @return true on success.
 */
static bool write_runtime_config(char* out_path, size_t out_path_len)
{
    FILE* fp = fopen(KEEL_RUNTIME_CONFIG_FILE, "w");
    if (!fp)
        return false;

    fprintf(fp,
        "# Auto-generated by test_proxy_ssv_e2e.c\n"
        "[keel]\n\n"
        "[worker_group.myapp]\n"
        "name = test\n"
        "bind_addr = 127.0.0.1\n"
        "bind_port = %d\n"
        "num_workers = 1\n"
        "worker_strategy = fixed\n"
        "distribution = round_robin\n"
        "max_conns_per_worker = 32\n"
        "max_conns_total = 64\n"
        "client_idle_timeout = 30s\n"
        "client_connect_timeout = 10s\n"
        "buffer_pool_size = 32MB\n"
        "arena_size = 32KB\n\n"
        "pool_mode = transaction\n"
        "min_pool_size = 1\n"
        "max_pool_size = 1\n"
        "idle_timeout = 30s\n"
        "query_timeout = 30s\n\n"
        "probe = postgres\n"
        "probe_interval = 2s\n"
        "probe_timeout = 2s\n"
        "probe_retries = 2\n"
        "probe_password = postgres\n"
        "failover_delay = 5s\n\n"
        "server_user = postgres\n"
        "server_password = postgres\n"
        "server_auth = md5\n"
        "auth_method = trust\n"
        "prepared_statement = tracking\n\n"
        "[worker_group.myapp.servers]\n"
        "primary = host=%s port=%u dbname=postgres role=primary weight=100\n",
        KEEL_PROXY_PORT,
        integ_get_node_host(1), integ_get_node_port(1));
    fclose(fp);

    strncpy(out_path, KEEL_RUNTIME_CONFIG_FILE, out_path_len - 1);
    out_path[out_path_len - 1] = '\0';
    return true;
}

/**
 * @brief Convenience: write_runtime_config() into a static buffer.
 *
 * @return Config file path, or NULL on failure.
 */
static const char* find_config_file(void)
{
    static char path[512];
    if (write_runtime_config(path, sizeof(path)))
        return path;
    return NULL;
}

/**
 * @brief Fork-exec the keel proxy and wait for it to accept connections.
 *
 * Polls the proxy listen port for up to PROXY_START_TIMEOUT_SEC seconds.
 * On success the child PID is stored in g_proxy_pid.  On timeout the
 * child is killed.
 *
 * @return true if the proxy started and accepted a test query.
 */
static bool start_proxy(void)
{
    const char* binary = find_proxy_binary();
    const char* config = find_config_file();
    if (!binary || !config)
        return false;

    pid_t pid = fork();
    if (pid < 0)
        return false;

    if (pid == 0) {
        if (!freopen("/tmp/keel_ssv_test.log", "w", stdout) ||
            !freopen("/tmp/keel_ssv_test.log", "a", stderr)) {
            _exit(2);
        }

        execl(binary, "keel", "-c", config, NULL);
        _exit(1);
    }

    g_proxy_pid = pid;
    for (int i = 0; i < PROXY_START_TIMEOUT_SEC; i++) {
        sleep(1);

        int status;
        pid_t result = waitpid(pid, &status, WNOHANG);
        if (result == pid) {
            g_proxy_pid = 0;
            return false;
        }

        integ_pg_conn_t* conn = integ_pg_connect(
            "127.0.0.1", KEEL_PROXY_PORT,
            "test", "test", "postgres");
        if (conn) {
            bool ok = integ_pg_exec(conn, "SELECT 1");
            integ_pg_close(conn);
            if (ok)
                return true;
        }
    }

    kill(pid, SIGTERM);
    sleep(1);
    kill(pid, SIGKILL);
    waitpid(pid, NULL, 0);
    g_proxy_pid = 0;
    return false;
}

/**
 * @brief Gracefully stop the keel proxy process launched by start_proxy().
 *
 * Sends SIGTERM, waits PROXY_STOP_TIMEOUT_SEC seconds, then escalates
 * to SIGKILL if still alive.
 */
static void stop_proxy(void)
{
    if (g_proxy_pid <= 0)
        return;

    kill(g_proxy_pid, SIGTERM);
    for (int i = 0; i < PROXY_STOP_TIMEOUT_SEC; i++) {
        int status;
        pid_t result = waitpid(g_proxy_pid, &status, WNOHANG);
        if (result == g_proxy_pid) {
            g_proxy_pid = 0;
            return;
        }
        sleep(1);
    }

    kill(g_proxy_pid, SIGKILL);
    waitpid(g_proxy_pid, NULL, 0);
    g_proxy_pid = 0;
}

/**
 * @brief Connect to the proxy with up to 3 retries.
 *
 * In transaction pool mode the proxy may close idle connections
 * due to DISCARD ALL + wake race; retries ride through the
 * transient state.
 *
 * @return Connected PG handle, or NULL.
 */
static integ_pg_conn_t* connect_proxy(void)
{
    /* In transaction pool mode with max_pool_size=1, the proxy may close
     * connections due to internal pool cycling (DISCARD ALL + wake race).
     * Retry with a short delay to ride through the transient state. */
    for (int attempt = 0; attempt < 10; attempt++) {
        integ_pg_conn_t* conn = integ_pg_connect("127.0.0.1", KEEL_PROXY_PORT,
                                                  TEST_USER, TEST_PASSWORD, TEST_DATABASE);
        if (!conn) {
            usleep(100000);  /* 100ms */
            continue;
        }
        if (integ_pg_exec(conn, "SELECT 1"))
            return conn;
        integ_pg_close(conn);
        usleep(100000);
    }
    return NULL;
}

/**
 * @brief Execute SQL and assert success, printing errors on failure.
 *
 * @param conn  Live PG connection.
 * @param sql   SQL statement to execute.
 */
static void assert_exec_ok(integ_pg_conn_t* conn, const char* sql)
{
    bool ok = integ_pg_exec(conn, sql);
    if (!ok)
        fprintf(stderr, "  exec FAILED: sql=[%s] err=[%s]\n", sql, integ_pg_last_error(conn));
    TEST_ASSERT(ok);
}

/* Execute SQL for cleanup/teardown — don't assert on failure since
 * pool-mode recycling may have already cleared the object. */
static void exec_cleanup(integ_pg_conn_t* conn, const char* sql)
{
    integ_pg_exec(conn, sql);
}

/**
 * @brief Execute SQL and fetch a single int64 result, asserting equality.
 *
 * @param conn      Live PG connection.
 * @param sql       Query that returns a single integer column.
 * @param expected  Expected value.
 */
static void assert_query_int_eq(integ_pg_conn_t* conn,
                                const char* sql,
                                int64_t expected)
{
    int64_t value = 0;
    bool ok = integ_pg_query_int(conn, sql, &value);
    if (!ok)
        fprintf(stderr, "  query FAILED: sql=[%s] err=[%s]\n", sql, integ_pg_last_error(conn));
    TEST_ASSERT(ok);
    TEST_ASSERT_EQ(value, expected);
}

/**
 * @brief Suite setup: ensure Docker cluster is running, then start proxy.
 *
 * Sets g_skip_tests if either step fails, causing all test functions
 * to skip gracefully rather than crash.
 */
static void setup(void)
{
    if (!integ_cluster_running()) {
        fprintf(stderr, "setup: cluster not running\n");
        if (!integ_docker_available()) {
            fprintf(stderr, "setup: docker not available\n");
            g_skip_tests = true;
            return;
        }

        if (!integ_cluster_start(true)) {
            fprintf(stderr, "setup: cluster start failed\n");
            g_skip_tests = true;
            return;
        }
        g_cluster_started_by_test = true;
    }

    if (!start_proxy()) {
        fprintf(stderr, "setup: start_proxy failed\n");
        g_skip_tests = true;
        return;
    }
}

/**
 * @brief Suite teardown: stop proxy and optionally tear down cluster.
 */
static void teardown(void)
{
    stop_proxy();
    if (g_cluster_started_by_test)
        integ_cluster_stop(false);
}

static void test_ssv_search_path_replays_prepared_stmt(void)
{
    TEST_BEGIN("proxy SSV: search_path change preserves prepared stmt semantics");

    if (g_skip_tests) {
        printf("SKIP\n");
        return;
    }

    integ_pg_conn_t* conn = connect_proxy();
    TEST_ASSERT_NOT_NULL(conn);
    if (!conn)
        return;

    assert_exec_ok(conn, "DROP SCHEMA IF EXISTS ssv_path_a CASCADE");
    assert_exec_ok(conn, "DROP SCHEMA IF EXISTS ssv_path_b CASCADE");
    assert_exec_ok(conn, "CREATE SCHEMA ssv_path_a");
    assert_exec_ok(conn, "CREATE SCHEMA ssv_path_b");
    assert_exec_ok(conn, "CREATE TABLE ssv_path_a.lookup (id int)");
    assert_exec_ok(conn, "CREATE TABLE ssv_path_b.lookup (id int)");
    assert_exec_ok(conn, "INSERT INTO ssv_path_a.lookup VALUES (1)");
    assert_exec_ok(conn, "INSERT INTO ssv_path_b.lookup VALUES (1), (2)");

    assert_exec_ok(conn, "SET search_path TO ssv_path_a, public");
    assert_exec_ok(conn, "PREPARE ssv_path_stmt AS SELECT COUNT(*) FROM lookup");
    assert_query_int_eq(conn, "EXECUTE ssv_path_stmt", 1);

    assert_exec_ok(conn, "SET search_path TO ssv_path_b, public");
    assert_query_int_eq(conn, "EXECUTE ssv_path_stmt", 2);

    assert_exec_ok(conn, "DEALLOCATE ssv_path_stmt");
    assert_exec_ok(conn, "RESET search_path");
    assert_exec_ok(conn, "DROP SCHEMA ssv_path_a CASCADE");
    assert_exec_ok(conn, "DROP SCHEMA ssv_path_b CASCADE");

    integ_pg_close(conn);
    TEST_END();
}

static void test_ssv_set_local_search_path_reverts_on_commit(void)
{
    TEST_BEGIN("proxy SSV: SET LOCAL search_path reverts on commit");

    if (g_skip_tests) {
        printf("SKIP\n");
        return;
    }

    integ_pg_conn_t* conn = connect_proxy();
    TEST_ASSERT_NOT_NULL(conn);
    if (!conn)
        return;

    assert_exec_ok(conn, "DROP SCHEMA IF EXISTS ssv_local_base CASCADE");
    assert_exec_ok(conn, "DROP SCHEMA IF EXISTS ssv_local_tx CASCADE");
    assert_exec_ok(conn, "CREATE SCHEMA ssv_local_base");
    assert_exec_ok(conn, "CREATE SCHEMA ssv_local_tx");
    assert_exec_ok(conn, "CREATE TABLE ssv_local_base.lookup (id int)");
    assert_exec_ok(conn, "CREATE TABLE ssv_local_tx.lookup (id int)");
    assert_exec_ok(conn, "INSERT INTO ssv_local_base.lookup VALUES (1)");
    assert_exec_ok(conn, "INSERT INTO ssv_local_tx.lookup VALUES (1), (2)");

    assert_exec_ok(conn, "SET search_path TO ssv_local_base, public");
    assert_exec_ok(conn, "PREPARE ssv_local_stmt AS SELECT COUNT(*) FROM lookup");
    assert_query_int_eq(conn, "EXECUTE ssv_local_stmt", 1);

    assert_exec_ok(conn, "BEGIN");
    assert_exec_ok(conn, "SET LOCAL search_path TO ssv_local_tx, public");
    assert_query_int_eq(conn, "EXECUTE ssv_local_stmt", 2);
    assert_exec_ok(conn, "COMMIT");
    assert_query_int_eq(conn, "EXECUTE ssv_local_stmt", 1);

    assert_exec_ok(conn, "DEALLOCATE ssv_local_stmt");
    assert_exec_ok(conn, "RESET search_path");
    assert_exec_ok(conn, "DROP SCHEMA ssv_local_base CASCADE");
    assert_exec_ok(conn, "DROP SCHEMA ssv_local_tx CASCADE");

    integ_pg_close(conn);
    TEST_END();
}

static void test_ssv_set_config_local_search_path_reverts_on_rollback(void)
{
    TEST_BEGIN("proxy SSV: set_config(search_path,...,true) reverts on rollback");

    if (g_skip_tests) {
        printf("SKIP\n");
        return;
    }

    integ_pg_conn_t* conn = connect_proxy();
    TEST_ASSERT_NOT_NULL(conn);
    if (!conn)
        return;

    assert_exec_ok(conn, "DROP SCHEMA IF EXISTS ssv_cfg_base CASCADE");
    assert_exec_ok(conn, "DROP SCHEMA IF EXISTS ssv_cfg_tx CASCADE");
    assert_exec_ok(conn, "CREATE SCHEMA ssv_cfg_base");
    assert_exec_ok(conn, "CREATE SCHEMA ssv_cfg_tx");
    assert_exec_ok(conn, "CREATE TABLE ssv_cfg_base.lookup (id int)");
    assert_exec_ok(conn, "CREATE TABLE ssv_cfg_tx.lookup (id int)");
    assert_exec_ok(conn, "INSERT INTO ssv_cfg_base.lookup VALUES (1)");
    assert_exec_ok(conn, "INSERT INTO ssv_cfg_tx.lookup VALUES (1), (2), (3)");

    assert_exec_ok(conn, "SET search_path TO ssv_cfg_base, public");
    assert_exec_ok(conn, "PREPARE ssv_cfg_stmt AS SELECT COUNT(*) FROM lookup");
    assert_query_int_eq(conn, "EXECUTE ssv_cfg_stmt", 1);

    assert_exec_ok(conn, "BEGIN");
    assert_exec_ok(conn,
        "SELECT set_config('search_path', 'ssv_cfg_tx, public', true)");
    assert_query_int_eq(conn, "EXECUTE ssv_cfg_stmt", 3);
    assert_exec_ok(conn, "ROLLBACK");
    assert_query_int_eq(conn, "EXECUTE ssv_cfg_stmt", 1);

    assert_exec_ok(conn, "DEALLOCATE ssv_cfg_stmt");
    assert_exec_ok(conn, "RESET search_path");
    assert_exec_ok(conn, "DROP SCHEMA ssv_cfg_base CASCADE");
    assert_exec_ok(conn, "DROP SCHEMA ssv_cfg_tx CASCADE");

    integ_pg_close(conn);
    TEST_END();
}

static void test_ssv_set_config_session_search_path_replays_prepared_stmt(void)
{
    TEST_BEGIN("proxy SSV: set_config(search_path,...,false) replays prepared stmt semantics");

    if (g_skip_tests) {
        printf("SKIP\n");
        return;
    }

    integ_pg_conn_t* conn = connect_proxy();
    TEST_ASSERT_NOT_NULL(conn);
    if (!conn)
        return;

    assert_exec_ok(conn, "DROP SCHEMA IF EXISTS ssv_func_a CASCADE");
    assert_exec_ok(conn, "DROP SCHEMA IF EXISTS ssv_func_b CASCADE");
    assert_exec_ok(conn, "CREATE SCHEMA ssv_func_a");
    assert_exec_ok(conn, "CREATE SCHEMA ssv_func_b");
    assert_exec_ok(conn, "CREATE TABLE ssv_func_a.lookup (id int)");
    assert_exec_ok(conn, "CREATE TABLE ssv_func_b.lookup (id int)");
    assert_exec_ok(conn, "INSERT INTO ssv_func_a.lookup VALUES (1)");
    assert_exec_ok(conn, "INSERT INTO ssv_func_b.lookup VALUES (1), (2), (3)");

    assert_exec_ok(conn,
        "SELECT set_config('search_path', 'ssv_func_a, public', false)");
    assert_exec_ok(conn, "PREPARE ssv_func_stmt AS SELECT COUNT(*) FROM lookup");
    assert_query_int_eq(conn, "EXECUTE ssv_func_stmt", 1);

    assert_exec_ok(conn,
        "SELECT set_config('search_path', 'ssv_func_b, public', false)");
    assert_query_int_eq(conn, "EXECUTE ssv_func_stmt", 3);

    assert_exec_ok(conn, "DEALLOCATE ssv_func_stmt");
    assert_exec_ok(conn, "RESET search_path");
    assert_exec_ok(conn, "DROP SCHEMA ssv_func_a CASCADE");
    assert_exec_ok(conn, "DROP SCHEMA ssv_func_b CASCADE");

    integ_pg_close(conn);
    TEST_END();
}

static void test_ssv_datestyle_replays_prepared_literal_semantics(void)
{
    TEST_BEGIN("proxy SSV: DateStyle change replays prepared literal semantics");

    if (g_skip_tests) {
        printf("SKIP\n");
        return;
    }

    integ_pg_conn_t* conn = connect_proxy();
    TEST_ASSERT_NOT_NULL(conn);
    if (!conn)
        return;

    assert_exec_ok(conn, "SET DateStyle TO 'ISO, MDY'");
    assert_exec_ok(conn,
        "PREPARE ssv_date_stmt AS SELECT EXTRACT(MONTH FROM '01/02/2003'::date)::int");
    assert_query_int_eq(conn, "EXECUTE ssv_date_stmt", 1);

    assert_exec_ok(conn, "SET DateStyle TO 'ISO, DMY'");
    assert_query_int_eq(conn, "EXECUTE ssv_date_stmt", 2);

    assert_exec_ok(conn, "DEALLOCATE ssv_date_stmt");
    assert_exec_ok(conn, "RESET DateStyle");

    integ_pg_close(conn);
    TEST_END();
}

static void test_ssv_timezone_replays_prepared_literal_semantics(void)
{
    TEST_BEGIN("proxy SSV: TimeZone change replays prepared timestamptz literal semantics");

    if (g_skip_tests) {
        printf("SKIP\n");
        return;
    }

    integ_pg_conn_t* conn = connect_proxy();
    TEST_ASSERT_NOT_NULL(conn);
    if (!conn)
        return;

    assert_exec_ok(conn, "SET TimeZone TO 'UTC'");
    assert_exec_ok(conn,
        "PREPARE ssv_tz_stmt AS SELECT EXTRACT(HOUR FROM ('2026-01-01 00:00:00'::timestamptz AT TIME ZONE 'UTC'))::int");
    assert_query_int_eq(conn, "EXECUTE ssv_tz_stmt", 0);

    assert_exec_ok(conn, "SET TimeZone TO 'America/New_York'");
    assert_query_int_eq(conn, "EXECUTE ssv_tz_stmt", 5);

    assert_exec_ok(conn, "DEALLOCATE ssv_tz_stmt");
    assert_exec_ok(conn, "RESET TimeZone");

    integ_pg_close(conn);
    TEST_END();
}

static void test_ssv_local_overlay_and_temp_shadow_revert_on_rollback(void)
{
    TEST_BEGIN("proxy SSV: local overlay plus temp shadow revert on rollback");

    if (g_skip_tests) {
        printf("SKIP\n");
        return;
    }

    integ_pg_conn_t* conn = connect_proxy();
    TEST_ASSERT_NOT_NULL(conn);
    if (!conn)
        return;

    assert_exec_ok(conn, "DROP TABLE IF EXISTS public.ssv_mix_target");
    assert_exec_ok(conn, "CREATE TABLE public.ssv_mix_target (id int)");
    assert_exec_ok(conn, "INSERT INTO public.ssv_mix_target VALUES (1), (2), (3), (4)");

    assert_exec_ok(conn, "PREPARE ssv_mix_stmt AS SELECT COUNT(*) FROM ssv_mix_target");
    assert_query_int_eq(conn, "EXECUTE ssv_mix_stmt", 4);

    assert_exec_ok(conn, "BEGIN");
    assert_exec_ok(conn,
        "SELECT set_config('search_path', 'pg_temp, public', true)");
    assert_exec_ok(conn, "CREATE TEMP TABLE ssv_mix_target (id int)");
    assert_exec_ok(conn, "INSERT INTO ssv_mix_target VALUES (1), (2)");
    assert_query_int_eq(conn, "EXECUTE ssv_mix_stmt", 2);
    assert_exec_ok(conn, "ROLLBACK");

    assert_query_int_eq(conn, "EXECUTE ssv_mix_stmt", 4);

    assert_exec_ok(conn, "DEALLOCATE ssv_mix_stmt");
    assert_exec_ok(conn, "DROP TABLE public.ssv_mix_target");

    integ_pg_close(conn);
    TEST_END();
}

static void test_ssv_temp_rollback_reverts_semantics(void)
{
    TEST_BEGIN("proxy SSV: rollback temp shadow reverts prepared stmt semantics");

    if (g_skip_tests) {
        printf("SKIP\n");
        return;
    }

    integ_pg_conn_t* conn = connect_proxy();
    TEST_ASSERT_NOT_NULL(conn);
    if (!conn)
        return;

    assert_exec_ok(conn, "DROP TABLE IF EXISTS public.ssv_rb_target");
    assert_exec_ok(conn, "CREATE TABLE public.ssv_rb_target (id int)");
    assert_exec_ok(conn, "INSERT INTO public.ssv_rb_target VALUES (1), (2), (3), (4)");

    assert_exec_ok(conn, "PREPARE ssv_rb_stmt AS SELECT COUNT(*) FROM ssv_rb_target");
    assert_query_int_eq(conn, "EXECUTE ssv_rb_stmt", 4);

    assert_exec_ok(conn, "BEGIN");
    assert_exec_ok(conn, "CREATE TEMP TABLE ssv_rb_target (id int)");
    assert_exec_ok(conn, "INSERT INTO ssv_rb_target VALUES (1), (2)");
    assert_query_int_eq(conn, "EXECUTE ssv_rb_stmt", 2);
    assert_exec_ok(conn, "ROLLBACK");

    assert_query_int_eq(conn, "EXECUTE ssv_rb_stmt", 4);

    assert_exec_ok(conn, "DEALLOCATE ssv_rb_stmt");
    assert_exec_ok(conn, "DROP TABLE public.ssv_rb_target");

    integ_pg_close(conn);
    TEST_END();
}

static void test_ssv_discard_temp_reverts_semantics(void)
{
    TEST_BEGIN("proxy SSV: DISCARD TEMP restores permanent-table prepared stmt semantics");

    if (g_skip_tests) {
        printf("SKIP\n");
        return;
    }

    integ_pg_conn_t* conn = connect_proxy();
    TEST_ASSERT_NOT_NULL(conn);
    if (!conn)
        return;

    assert_exec_ok(conn, "DROP TABLE IF EXISTS public.ssv_discard_target");
    assert_exec_ok(conn, "CREATE TABLE public.ssv_discard_target (id int)");
    assert_exec_ok(conn, "INSERT INTO public.ssv_discard_target VALUES (1), (2), (3), (4), (5)");

    assert_exec_ok(conn, "PREPARE ssv_discard_stmt AS SELECT COUNT(*) FROM ssv_discard_target");
    assert_query_int_eq(conn, "EXECUTE ssv_discard_stmt", 5);

    assert_exec_ok(conn, "CREATE TEMP TABLE ssv_discard_target (id int)");
    assert_exec_ok(conn, "INSERT INTO ssv_discard_target VALUES (1), (2), (3)");
    assert_query_int_eq(conn, "EXECUTE ssv_discard_stmt", 3);

    assert_exec_ok(conn, "DISCARD TEMP");
    assert_query_int_eq(conn, "EXECUTE ssv_discard_stmt", 5);

    assert_exec_ok(conn, "DEALLOCATE ssv_discard_stmt");
    assert_exec_ok(conn, "DROP TABLE public.ssv_discard_target");

    integ_pg_close(conn);
    TEST_END();
}

/* ---------------------------------------------------------------------------
 * Edge-case stress tests (Phase 2 validation priorities §20.5)
 * ---------------------------------------------------------------------------
 * These exercise the most subtle SSV interactions: ugly transaction-end
 * sequences mixing SET LOCAL, PREPARE, temp DDL, ROLLBACK, and replay
 * on a potentially different backend.
 * ---------------------------------------------------------------------------*/

/**
 * The exact sequence called out as the highest-risk edge case:
 *   BEGIN → SET LOCAL datestyle → PREPARE → temp DDL → ROLLBACK
 * After ROLLBACK both the SET LOCAL overlay AND the temp table must revert,
 * and executing the prepared stmt on a new backend must use the session-level
 * DateStyle (not the rolled-back local overlay).
 */
static void test_ssv_ugly_begin_setlocal_prepare_tempdll_rollback(void)
{
    TEST_BEGIN("proxy SSV: BEGIN + SET LOCAL + PREPARE + temp DDL + ROLLBACK replay");

    if (g_skip_tests) { printf("SKIP\n"); return; }

    integ_pg_conn_t* conn = connect_proxy();
    TEST_ASSERT_NOT_NULL(conn);
    if (!conn) return;

    /* Baseline: session-level DateStyle = ISO, MDY (month-first) */
    assert_exec_ok(conn, "SET DateStyle TO 'ISO, MDY'");

    /* Create a permanent target so we can also check temp-shadow reversion */
    assert_exec_ok(conn, "DROP TABLE IF EXISTS public.ssv_ugly_target");
    assert_exec_ok(conn, "CREATE TABLE public.ssv_ugly_target (id int)");
    assert_exec_ok(conn, "INSERT INTO public.ssv_ugly_target VALUES (1), (2), (3)");

    /* Prepare two stmts under the session-level context */
    assert_exec_ok(conn,
        "PREPARE ssv_ugly_date AS SELECT EXTRACT(MONTH FROM '01/02/2003'::date)::int");
    assert_exec_ok(conn,
        "PREPARE ssv_ugly_count AS SELECT COUNT(*) FROM ssv_ugly_target");

    /* Verify baseline */
    assert_query_int_eq(conn, "EXECUTE ssv_ugly_date", 1);   /* MDY → month=1 */
    assert_query_int_eq(conn, "EXECUTE ssv_ugly_count", 3);

    /* The ugly sequence */
    assert_exec_ok(conn, "BEGIN");
    assert_exec_ok(conn, "SET LOCAL DateStyle TO 'ISO, DMY'");
    /* DateStyle is a parse-time GUC: the PREPARE above already froze the
     * date literal under MDY.  SET LOCAL within the same pinned-backend
     * transaction does NOT re-parse, so the result stays month=1 (MDY). */
    assert_query_int_eq(conn, "EXECUTE ssv_ugly_date", 1);   /* parse-time: still MDY */
    /* Create temp table that shadows the permanent one */
    assert_exec_ok(conn, "CREATE TEMP TABLE ssv_ugly_target (id int)");
    assert_exec_ok(conn, "INSERT INTO ssv_ugly_target VALUES (1)");
    assert_query_int_eq(conn, "EXECUTE ssv_ugly_count", 1);  /* temp shadow */
    /* ROLLBACK reverts both SET LOCAL and temp table */
    assert_exec_ok(conn, "ROLLBACK");

    /* After rollback: session-level DateStyle (MDY) restored, temp gone */
    assert_query_int_eq(conn, "EXECUTE ssv_ugly_date", 1);   /* MDY → month=1 */
    assert_query_int_eq(conn, "EXECUTE ssv_ugly_count", 3);  /* permanent table */

    assert_exec_ok(conn, "DEALLOCATE ssv_ugly_date");
    assert_exec_ok(conn, "DEALLOCATE ssv_ugly_count");
    assert_exec_ok(conn, "RESET DateStyle");
    assert_exec_ok(conn, "DROP TABLE public.ssv_ugly_target");

    integ_pg_close(conn);
    TEST_END();
}

/**
 * Multiple replay-sensitive GUCs change together:
 *   SET DateStyle + SET TimeZone between two EXECUTE calls.
 * Both must be replayed correctly on the new backend.
 */
static void test_ssv_multi_guc_change_replays_correctly(void)
{
    TEST_BEGIN("proxy SSV: multiple GUC changes replay together");

    if (g_skip_tests) { printf("SKIP\n"); return; }

    integ_pg_conn_t* conn = connect_proxy();
    TEST_ASSERT_NOT_NULL(conn);
    if (!conn) return;

    assert_exec_ok(conn, "SET DateStyle TO 'ISO, MDY'");
    assert_exec_ok(conn, "SET TimeZone TO 'UTC'");

    assert_exec_ok(conn,
        "PREPARE ssv_multi_date AS SELECT EXTRACT(MONTH FROM '01/02/2003'::date)::int");
    assert_exec_ok(conn,
        "PREPARE ssv_multi_tz AS SELECT EXTRACT(HOUR FROM "
        "('2026-01-01 00:00:00'::timestamptz AT TIME ZONE 'UTC'))::int");

    assert_query_int_eq(conn, "EXECUTE ssv_multi_date", 1);
    assert_query_int_eq(conn, "EXECUTE ssv_multi_tz", 0);

    /* Change BOTH GUCs between executes */
    assert_exec_ok(conn, "SET DateStyle TO 'ISO, DMY'");
    assert_exec_ok(conn, "SET TimeZone TO 'America/New_York'");

    assert_query_int_eq(conn, "EXECUTE ssv_multi_date", 2);
    assert_query_int_eq(conn, "EXECUTE ssv_multi_tz", 5);

    assert_exec_ok(conn, "DEALLOCATE ssv_multi_date");
    assert_exec_ok(conn, "DEALLOCATE ssv_multi_tz");
    assert_exec_ok(conn, "RESET DateStyle");
    assert_exec_ok(conn, "RESET TimeZone");

    integ_pg_close(conn);
    TEST_END();
}

/**
 * PREPARE inside a transaction with SET LOCAL active, then COMMIT,
 * then EXECUTE.  The stmt was prepared under the local overlay, but after
 * commit the overlay reverts.
 *
 * Known limitation (Phase 2 gap §20.2): DateStyle is parse-time, so the
 * backend's prepared plan retains the DMY semantics even after SET LOCAL
 * reverts on COMMIT.  The backend is stamped with the post-revert hash,
 * preventing re-preparation.  This test documents current behavior.
 */
static void test_ssv_prepare_under_local_overlay_then_commit(void)
{
    TEST_BEGIN("proxy SSV: PREPARE under SET LOCAL overlay then COMMIT + EXECUTE");

    if (g_skip_tests) { printf("SKIP\n"); return; }

    integ_pg_conn_t* conn = connect_proxy();
    TEST_ASSERT_NOT_NULL(conn);
    if (!conn) return;

    assert_exec_ok(conn, "SET DateStyle TO 'ISO, MDY'");

    assert_exec_ok(conn, "BEGIN");
    assert_exec_ok(conn, "SET LOCAL DateStyle TO 'ISO, DMY'");
    /* PREPARE while DMY is active */
    assert_exec_ok(conn,
        "PREPARE ssv_overlay_prep AS SELECT EXTRACT(MONTH FROM '01/02/2003'::date)::int");
    assert_query_int_eq(conn, "EXECUTE ssv_overlay_prep", 2);  /* DMY → 2 */
    assert_exec_ok(conn, "COMMIT");

    /* After commit, session DateStyle is MDY again, but the backend's plan
     * was parsed under DMY and retains those semantics (parse-time GUC).
     * Phase 2 will address re-preparation after SET LOCAL reverts. */
    assert_query_int_eq(conn, "EXECUTE ssv_overlay_prep", 2);  /* retains DMY plan */

    exec_cleanup(conn, "DEALLOCATE ssv_overlay_prep");
    exec_cleanup(conn, "RESET DateStyle");

    integ_pg_close(conn);
    TEST_END();
}

/**
 * Non-temp DDL that changes prepared statement meaning:
 *   PREPARE over a table, ALTER TABLE ADD COLUMN with DEFAULT,
 *   then EXECUTE.  The stmt should still return the original column
 *   semantics (COUNT(*) is stable across ALTER ADD) but validates
 *   that KEEL correctly handles DDL between PREPARE and EXECUTE.
 */
static void test_ssv_non_temp_ddl_between_prepare_execute(void)
{
    TEST_BEGIN("proxy SSV: non-temp DDL between PREPARE and EXECUTE");

    if (g_skip_tests) { printf("SKIP\n"); return; }

    integ_pg_conn_t* conn = connect_proxy();
    TEST_ASSERT_NOT_NULL(conn);
    if (!conn) return;

    assert_exec_ok(conn, "DROP TABLE IF EXISTS public.ssv_ddl_target");
    assert_exec_ok(conn, "CREATE TABLE public.ssv_ddl_target (id int)");
    assert_exec_ok(conn, "INSERT INTO public.ssv_ddl_target VALUES (1), (2), (3)");

    assert_exec_ok(conn,
        "PREPARE ssv_ddl_stmt AS SELECT COUNT(*) FROM ssv_ddl_target");
    assert_query_int_eq(conn, "EXECUTE ssv_ddl_stmt", 3);

    /* ALTER TABLE adds a column — does not change row count */
    assert_exec_ok(conn,
        "ALTER TABLE public.ssv_ddl_target ADD COLUMN label text DEFAULT 'x'");
    assert_query_int_eq(conn, "EXECUTE ssv_ddl_stmt", 3);

    /* INSERT rows after DDL */
    assert_exec_ok(conn, "INSERT INTO public.ssv_ddl_target (id) VALUES (4), (5)");
    assert_query_int_eq(conn, "EXECUTE ssv_ddl_stmt", 5);

    assert_exec_ok(conn, "DEALLOCATE ssv_ddl_stmt");
    assert_exec_ok(conn, "DROP TABLE public.ssv_ddl_target");

    integ_pg_close(conn);
    TEST_END();
}

/**
 * Multiple PREPARE + DEALLOCATE cycles interleaved with GUC changes.
 * Uses search_path (execute-time resolution) so that GUC changes are
 * reflected immediately even after DEALLOCATE+PREPARE cycles, without
 * depending on re-preparation (which DateStyle would require).
 */
static void test_ssv_interleaved_prepare_deallocate_guc_changes(void)
{
    TEST_BEGIN("proxy SSV: interleaved PREPARE/DEALLOCATE with GUC changes");

    if (g_skip_tests) { printf("SKIP\n"); return; }

    integ_pg_conn_t* conn = connect_proxy();
    TEST_ASSERT_NOT_NULL(conn);
    if (!conn) return;

    /* Set up two schemas with different row counts */
    assert_exec_ok(conn, "DROP SCHEMA IF EXISTS ssv_intlv_a CASCADE");
    assert_exec_ok(conn, "DROP SCHEMA IF EXISTS ssv_intlv_b CASCADE");
    assert_exec_ok(conn, "CREATE SCHEMA ssv_intlv_a");
    assert_exec_ok(conn, "CREATE SCHEMA ssv_intlv_b");
    assert_exec_ok(conn, "CREATE TABLE ssv_intlv_a.tbl (id int)");
    assert_exec_ok(conn, "CREATE TABLE ssv_intlv_b.tbl (id int)");
    assert_exec_ok(conn, "INSERT INTO ssv_intlv_a.tbl VALUES (1)");
    assert_exec_ok(conn, "INSERT INTO ssv_intlv_b.tbl VALUES (1), (2), (3)");

    assert_exec_ok(conn, "SET search_path TO ssv_intlv_a, public");

    /* First stmt under schema A */
    assert_exec_ok(conn,
        "PREPARE ssv_intlv_s1 AS SELECT COUNT(*) FROM tbl");
    assert_query_int_eq(conn, "EXECUTE ssv_intlv_s1", 1);

    /* Change to schema B, add second stmt */
    assert_exec_ok(conn, "SET search_path TO ssv_intlv_b, public");
    assert_exec_ok(conn,
        "PREPARE ssv_intlv_s2 AS SELECT COUNT(*) FROM tbl");

    /* Both stmts now resolve to schema B (search_path is execute-time) */
    assert_query_int_eq(conn, "EXECUTE ssv_intlv_s1", 3);
    assert_query_int_eq(conn, "EXECUTE ssv_intlv_s2", 3);

    /* Deallocate first, keep second */
    assert_exec_ok(conn, "DEALLOCATE ssv_intlv_s1");

    /* Change back to schema A — second stmt should now resolve to A */
    assert_exec_ok(conn, "SET search_path TO ssv_intlv_a, public");
    assert_query_int_eq(conn, "EXECUTE ssv_intlv_s2", 1);

    assert_exec_ok(conn, "DEALLOCATE ssv_intlv_s2");
    assert_exec_ok(conn, "RESET search_path");
    assert_exec_ok(conn, "DROP SCHEMA ssv_intlv_a CASCADE");
    assert_exec_ok(conn, "DROP SCHEMA ssv_intlv_b CASCADE");

    integ_pg_close(conn);
    TEST_END();
}

/**
 * SET LOCAL inside a failed transaction (error state).
 * After ROLLBACK the overlay must revert and replay must use
 * the session-level value.
 */
static void test_ssv_set_local_in_failed_tx_rollback(void)
{
    TEST_BEGIN("proxy SSV: SET LOCAL in failed transaction reverts on ROLLBACK");

    if (g_skip_tests) { printf("SKIP\n"); return; }

    integ_pg_conn_t* conn = connect_proxy();
    TEST_ASSERT_NOT_NULL(conn);
    if (!conn) return;

    assert_exec_ok(conn, "SET DateStyle TO 'ISO, MDY'");
    assert_exec_ok(conn,
        "PREPARE ssv_errtx_stmt AS SELECT EXTRACT(MONTH FROM '01/02/2003'::date)::int");
    assert_query_int_eq(conn, "EXECUTE ssv_errtx_stmt", 1);

    assert_exec_ok(conn, "BEGIN");
    assert_exec_ok(conn, "SET LOCAL DateStyle TO 'ISO, DMY'");
    /* DateStyle is parse-time: the plan was frozen under MDY at PREPARE,
     * so SET LOCAL within the pinned-backend tx does not change results. */
    assert_query_int_eq(conn, "EXECUTE ssv_errtx_stmt", 1);  /* parse-time: still MDY */

    /* Force an error to put the tx in aborted state */
    integ_pg_exec(conn, "SELECT 1/0");  /* division by zero — may fail */
    /* Transaction is now in error state, ROLLBACK is the only option */
    assert_exec_ok(conn, "ROLLBACK");

    /* Session-level MDY must be back */
    assert_query_int_eq(conn, "EXECUTE ssv_errtx_stmt", 1);

    exec_cleanup(conn, "DEALLOCATE ssv_errtx_stmt");
    exec_cleanup(conn, "RESET DateStyle");

    integ_pg_close(conn);
    TEST_END();
}

/**
 * Rapid SET/RESET cycles: change a GUC multiple times without executing
 * the prepared stmt in between, then EXECUTE.  The final effective
 * value must be used.
 */
static void test_ssv_rapid_guc_toggle(void)
{
    TEST_BEGIN("proxy SSV: rapid SET/RESET toggles use final effective value");

    if (g_skip_tests) { printf("SKIP\n"); return; }

    integ_pg_conn_t* conn = connect_proxy();
    TEST_ASSERT_NOT_NULL(conn);
    if (!conn) return;

    assert_exec_ok(conn, "SET DateStyle TO 'ISO, MDY'");
    assert_exec_ok(conn,
        "PREPARE ssv_toggle_stmt AS SELECT EXTRACT(MONTH FROM '01/02/2003'::date)::int");

    /* Toggle back and forth multiple times */
    assert_exec_ok(conn, "SET DateStyle TO 'ISO, DMY'");
    assert_exec_ok(conn, "SET DateStyle TO 'ISO, MDY'");
    assert_exec_ok(conn, "SET DateStyle TO 'ISO, DMY'");
    assert_exec_ok(conn, "SET DateStyle TO 'ISO, MDY'");
    assert_exec_ok(conn, "SET DateStyle TO 'ISO, DMY'");  /* final: DMY */

    assert_query_int_eq(conn, "EXECUTE ssv_toggle_stmt", 2);

    /* Toggle back to MDY */
    assert_exec_ok(conn, "SET DateStyle TO 'ISO, MDY'");
    assert_query_int_eq(conn, "EXECUTE ssv_toggle_stmt", 1);

    assert_exec_ok(conn, "DEALLOCATE ssv_toggle_stmt");
    assert_exec_ok(conn, "RESET DateStyle");

    integ_pg_close(conn);
    TEST_END();
}

int main(void)
{
    signal(SIGPIPE, SIG_IGN);

    printf("=== KEEL Proxy SSV End-to-End Tests ===\n\n");
    printf("These tests start a dedicated single-backend proxy instance and");
    printf(" validate semantic stmt replay through the real PostgreSQL stack.\n\n");

    setup();

    if (g_skip_tests) {
        printf("\nNo tests run - see above for reason\n");
        return 0;
    }

    /* Core SSV tests */
    test_ssv_search_path_replays_prepared_stmt();
    test_ssv_set_local_search_path_reverts_on_commit();
    test_ssv_set_config_local_search_path_reverts_on_rollback();
    test_ssv_set_config_session_search_path_replays_prepared_stmt();
    test_ssv_datestyle_replays_prepared_literal_semantics();
    test_ssv_timezone_replays_prepared_literal_semantics();
    test_ssv_local_overlay_and_temp_shadow_revert_on_rollback();
    test_ssv_temp_rollback_reverts_semantics();
    test_ssv_discard_temp_reverts_semantics();

    /* Edge-case stress tests (Phase 2 §20.5 priorities) */
    test_ssv_ugly_begin_setlocal_prepare_tempdll_rollback();
    test_ssv_multi_guc_change_replays_correctly();
    test_ssv_prepare_under_local_overlay_then_commit();
    test_ssv_non_temp_ddl_between_prepare_execute();
    test_ssv_interleaved_prepare_deallocate_guc_changes();
    test_ssv_set_local_in_failed_tx_rollback();
    test_ssv_rapid_guc_toggle();

    teardown();

    printf("\n");
    return test_summary();
}