/**
 * @file test_proxy_e2e.c
 * @brief Full-stack proxy integration tests with real process orchestration.
 *
 * This suite boots KEEL as a child process, drives traffic through the proxy,
 * and validates external behavior from the client side. It therefore exercises
 * cross-layer integration that unit tests cannot observe in isolation: runtime
 * config loading, worker startup, backend probing, auth flow, and query routing
 * under a live parent/child process lifecycle.
 *
 * The tests deliberately favor deterministic orchestration over maximal load.
 * Their value is confidence that the assembled system starts, accepts traffic,
 * and shuts down cleanly across repeated runs.
 */

#include "test_utils.h"
#include "test_integration.h"

#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <signal.h>
#include <sys/wait.h>
#include <errno.h>
#include <limits.h>

/* ============================================================================
 * Configuration
 * ============================================================================ */

/* KEEL proxy configuration */
#define KEEL_PROXY_PORT      16432
#define KEEL_CONFIG_FILE     "keel_test.ini"
#define KEEL_BINARY          "keel"

/* Test credentials - proxy uses hardcoded test/test user with MD5 auth */
#define TEST_USER           "test"
#define TEST_PASSWORD       "test"
#define TEST_DATABASE       "postgres"

/* Timeouts */
#define PROXY_START_TIMEOUT_SEC     10
#define PROXY_STOP_TIMEOUT_SEC      5

#define KEEL_RUNTIME_CONFIG_FILE "/tmp/keel_test_runtime.ini"

/* ============================================================================
 * Proxy Process Management
 * ============================================================================ */

static pid_t g_proxy_pid = 0;
static bool g_cluster_started_by_test = false;
static bool g_skip_tests = false;

/**
 * @brief Locate an executable KEEL proxy binary in common build/runtime paths.
 * @return Absolute or relative executable path, or `NULL` if not found.
 */
static const char* find_proxy_binary(void) {
    static char path[PATH_MAX];
    
    /* Try relative paths from test binary location */
    const char* candidates[] = {
        "../src/main/keel",           /* In build/tests/ */
        "../../build/src/main/keel",   /* In source/tests/ */
        "./keel",                       /* Current dir */
        NULL
    };
    
    for (int i = 0; candidates[i]; i++) {
        if (access(candidates[i], X_OK) == 0) {
            /* Get absolute path */
            if (realpath(candidates[i], path)) {
                return path;
            }
            return candidates[i];
        }
    }
    
    /* Try PATH */
    FILE* fp = popen("which keel 2>/dev/null", "r");
    if (fp) {
        if (fgets(path, sizeof(path), fp)) {
            path[strcspn(path, "\n")] = '\0';
            pclose(fp);
            if (access(path, X_OK) == 0) {
                return path;
            }
        }
        pclose(fp);
    }
    
    return NULL;
}

/**
 * @brief Generate a runtime config wired to the currently discovered test
 *        cluster endpoints.
 * @param out_path [out] Receives the config path.
 * @param out_path_len Capacity of `out_path`.
 * @return `true` on success, `false` otherwise.
 *
 * Generating this file at runtime avoids stale endpoint assumptions and keeps
 * the proxy e2e suite aligned with whatever ports the integration harness has
 * actually selected for primary and replicas.
 */
static bool write_runtime_config(char* out_path, size_t out_path_len) {
    FILE* fp = fopen(KEEL_RUNTIME_CONFIG_FILE, "w");
    if (!fp) {
        fprintf(stderr, "ERROR: failed to create runtime config %s: %s\n",
                KEEL_RUNTIME_CONFIG_FILE, strerror(errno));
        return false;
    }

    fprintf(fp,
        "# Auto-generated by test_proxy_e2e.c\n"
        "[keel]\n"
        "log_level = 3\n\n"
        "[worker_group.myapp]\n"
        "name = test\n"
        "bind_addr = 127.0.0.1\n"
        "bind_port = %d\n"
        "num_workers = 2\n"
        "worker_strategy = fixed\n"
        "distribution = round_robin\n"
        "max_conns_per_worker = 100\n"
        "max_conns_total = 200\n"
        "client_idle_timeout = 30s\n"
        "client_connect_timeout = 10s\n"
        "buffer_pool_size = 64MB\n"
        "arena_size = 32KB\n\n"
        "pool_mode = transaction\n"
        "min_pool_size = 2\n"
        "max_pool_size = 10\n"
        "idle_timeout = 30s\n"
        "query_timeout = 30s\n\n"
        "probe = postgres\n"
        "probe_interval = 2s\n"
        "probe_timeout = 2s\n"
        "probe_retries = 2\n"
        "failover_delay = 5s\n\n"
        "server_user = postgres\n"
        "server_password = postgres\n"
        "server_auth = scram-sha-256\n\n"
        "[worker_group.myapp.servers]\n"
        "primary  = host=%s port=%u dbname=postgres role=primary weight=100\n"
        "replica1 = host=%s port=%u dbname=postgres role=replica weight=100\n"
        "replica2 = host=%s port=%u dbname=postgres role=replica weight=100\n",
        KEEL_PROXY_PORT,
        integ_get_node_host(1), integ_get_node_port(1),
        integ_get_node_host(2), integ_get_node_port(2),
        integ_get_node_host(3), integ_get_node_port(3));
    fclose(fp);

    strncpy(out_path, KEEL_RUNTIME_CONFIG_FILE, out_path_len - 1);
    out_path[out_path_len - 1] = '\0';
    return true;
}

/**
 * @brief Materialize and return the runtime config path for proxy startup.
 * @return Config path on success, otherwise `NULL`.
 */
static const char* find_config_file(void) {
    static char path[512];
    if (write_runtime_config(path, sizeof(path)))
        return path;
    return NULL;
}

/**
 * @brief Fork and start the KEEL proxy, then poll readiness via real client
 *        connections.
 * @return `true` if the proxy becomes query-ready before timeout.
 *
 * Readiness is defined as successful connect plus `SELECT 1`, not just process
 * liveness. This avoids false positives where the process exists but workers or
 * backend probing are not yet operational.
 */
static bool start_proxy(void) {
    const char* binary = find_proxy_binary();
    if (!binary) {
        fprintf(stderr, "ERROR: KEEL proxy binary not found\n");
        fprintf(stderr, "       Build the project first: cmake --build build\n");
        return false;
    }
    
    const char* config = find_config_file();
    if (!config) {
        fprintf(stderr, "ERROR: Test config file not found: %s\n", KEEL_CONFIG_FILE);
        return false;
    }
    
    printf("Starting proxy: %s -c %s\n", binary, config);
    
    pid_t pid = fork();
    if (pid < 0) {
        fprintf(stderr, "ERROR: fork() failed: %s\n", strerror(errno));
        return false;
    }
    
    if (pid == 0) {
        /* Child process - exec the proxy */
        /* Redirect stdout/stderr to log file */
        if (!freopen("/tmp/keel_test.log", "w", stdout) ||
            !freopen("/tmp/keel_test.log", "a", stderr)) {
            _exit(2);
        }
        
        execl(binary, "keel", "-c", config, NULL);
        
        /* exec failed */
        fprintf(stderr, "ERROR: exec failed: %s\n", strerror(errno));
        _exit(1);
    }
    
    /* Parent process */
    g_proxy_pid = pid;
    
    /* Wait for proxy to be ready */
    for (int i = 0; i < PROXY_START_TIMEOUT_SEC; i++) {
        sleep(1);
        
        /* Check if process is still running */
        int status;
        pid_t result = waitpid(pid, &status, WNOHANG);
        if (result == pid) {
            /* Process exited */
            fprintf(stderr, "ERROR: Proxy exited prematurely with status %d\n", 
                    WEXITSTATUS(status));
            fprintf(stderr, "       Check /tmp/keel_test.log for details\n");
            g_proxy_pid = 0;
            return false;
        }
        
        /* Try to connect to proxy */
        integ_pg_conn_t* conn = integ_pg_connect(
            "127.0.0.1", KEEL_PROXY_PORT,
            TEST_USER, TEST_PASSWORD, TEST_DATABASE
        );
        
        if (conn) {
            bool ok = integ_pg_exec(conn, "SELECT 1");
            integ_pg_close(conn);
            if (ok) {
                printf("Proxy ready after %d seconds\n", i + 1);
                return true;
            }
        }
        
        printf("Waiting for proxy... (%d/%d)\n", i + 1, PROXY_START_TIMEOUT_SEC);
    }
    
    fprintf(stderr, "ERROR: Proxy did not become ready in %d seconds\n", 
            PROXY_START_TIMEOUT_SEC);
    fprintf(stderr, "       Check /tmp/keel_test.log for details\n");
    
    /* Kill the hung process */
    kill(pid, SIGTERM);
    sleep(1);
    kill(pid, SIGKILL);
    waitpid(pid, NULL, 0);
    g_proxy_pid = 0;
    
    return false;
}

/**
 * @brief Gracefully stop the proxy process with a forced-kill fallback.
 * @return
 */
static void stop_proxy(void) {
    if (g_proxy_pid <= 0) return;
    
    printf("Stopping proxy (PID %d)...\n", g_proxy_pid);
    
    /* Send SIGTERM first for graceful shutdown */
    kill(g_proxy_pid, SIGTERM);
    
    /* Wait for process to exit */
    for (int i = 0; i < PROXY_STOP_TIMEOUT_SEC; i++) {
        int status;
        pid_t result = waitpid(g_proxy_pid, &status, WNOHANG);
        if (result == g_proxy_pid) {
            printf("Proxy stopped (exit status %d)\n", WEXITSTATUS(status));
            g_proxy_pid = 0;
            return;
        }
        sleep(1);
    }
    
    /* Force kill */
    printf("Force killing proxy...\n");
    kill(g_proxy_pid, SIGKILL);
    waitpid(g_proxy_pid, NULL, 0);
    g_proxy_pid = 0;
}

/* ============================================================================
 * Test Setup/Teardown
 * ============================================================================ */

static void setup(void) {
    if (!integ_cluster_running()) {
        if (!integ_docker_available()) {
            printf("SKIP: Docker not available and no live cluster detected\n");
            g_skip_tests = true;
            return;
        }

        printf("Starting PostgreSQL cluster via Docker...\n");
        if (!integ_cluster_start(true)) {
            printf("SKIP: Failed to start PostgreSQL cluster\n");
            g_skip_tests = true;
            return;
        }
        g_cluster_started_by_test = true;
        printf("PostgreSQL cluster started\n");
    } else {
        printf("PostgreSQL cluster already running\n");
    }
    
    /* Start the KEEL proxy */
    if (!start_proxy()) {
        printf("SKIP: Failed to start KEEL proxy\n");
        g_skip_tests = true;
        return;
    }
    
    printf("\n=== Test environment ready ===\n");
    printf("PostgreSQL primary: %s:%u\n", integ_get_primary_host(), integ_get_primary_port());
    printf("KEEL proxy:          127.0.0.1:%d\n\n", KEEL_PROXY_PORT);
}

static void teardown(void) {
    stop_proxy();
    
    if (g_cluster_started_by_test) {
        printf("Stopping PostgreSQL cluster...\n");
        integ_cluster_stop(false);  /* Keep volumes for faster restart */
    }
}

/* ============================================================================
 * Basic Connection Tests via Proxy
 * ============================================================================ */

static void test_proxy_connect(void) {
    TEST_BEGIN("connect through proxy");
    
    if (g_skip_tests) {
        printf("SKIP\n");
        return;
    }
    
    integ_pg_conn_t* conn = integ_pg_connect(
        "127.0.0.1", KEEL_PROXY_PORT,
        TEST_USER, TEST_PASSWORD, TEST_DATABASE
    );
    
    TEST_ASSERT_NOT_NULL(conn);
    if (conn) {
        TEST_ASSERT(integ_pg_is_alive(conn));
        integ_pg_close(conn);
    }
    
    TEST_END();
}

static void test_proxy_simple_query(void) {
    TEST_BEGIN("simple query through proxy");
    
    if (g_skip_tests) {
        printf("SKIP\n");
        return;
    }
    
    integ_pg_conn_t* conn = integ_pg_connect(
        "127.0.0.1", KEEL_PROXY_PORT,
        TEST_USER, TEST_PASSWORD, TEST_DATABASE
    );
    
    TEST_ASSERT_NOT_NULL(conn);
    if (!conn) return;
    
    int64_t result;
    bool ok = integ_pg_query_int(conn, "SELECT 42", &result);
    TEST_ASSERT(ok);
    TEST_ASSERT_EQ(result, 42);
    
    integ_pg_close(conn);
    
    TEST_END();
}

static void test_proxy_string_query(void) {
    TEST_BEGIN("string query through proxy");
    
    if (g_skip_tests) {
        printf("SKIP\n");
        return;
    }
    
    integ_pg_conn_t* conn = integ_pg_connect(
        "127.0.0.1", KEEL_PROXY_PORT,
        TEST_USER, TEST_PASSWORD, TEST_DATABASE
    );
    
    TEST_ASSERT_NOT_NULL(conn);
    if (!conn) return;
    
    char result[256];
    bool ok = integ_pg_query_string(conn, "SELECT 'hello from proxy'", result, sizeof(result));
    TEST_ASSERT(ok);
    TEST_ASSERT_STR_EQ(result, "hello from proxy");
    
    integ_pg_close(conn);
    
    TEST_END();
}

/* ============================================================================
 * Connection Pooling Tests
 * ============================================================================ */

static void test_pool_multiple_connections(void) {
    TEST_BEGIN("multiple connections through proxy (tests backend_pool.c)");
    
    if (g_skip_tests) {
        printf("SKIP\n");
        return;
    }
    
    /* Open multiple connections to exercise connection pooling */
    #define POOL_TEST_CONNS 10
    integ_pg_conn_t* conns[POOL_TEST_CONNS] = {0};
    
    /* Connect all */
    for (int i = 0; i < POOL_TEST_CONNS; i++) {
        conns[i] = integ_pg_connect(
            "127.0.0.1", KEEL_PROXY_PORT,
            TEST_USER, TEST_PASSWORD, TEST_DATABASE
        );
        TEST_ASSERT_NOT_NULL(conns[i]);
    }
    
    /* Execute queries on all connections */
    for (int i = 0; i < POOL_TEST_CONNS; i++) {
        if (!conns[i]) continue;
        
        int64_t result;
        char query[64];
        snprintf(query, sizeof(query), "SELECT %d * 10", i);
        
        bool ok = integ_pg_query_int(conns[i], query, &result);
        TEST_ASSERT(ok);
        TEST_ASSERT_EQ(result, i * 10);
    }
    
    /* Close all */
    for (int i = 0; i < POOL_TEST_CONNS; i++) {
        integ_pg_close(conns[i]);
    }
    
    TEST_END();
}

static void test_pool_connection_reuse(void) {
    TEST_BEGIN("connection reuse through proxy (tests backend_pool.c)");
    
    if (g_skip_tests) {
        printf("SKIP\n");
        return;
    }
    
    /* Connect, query, disconnect - repeat to test connection reuse */
    for (int round = 0; round < 5; round++) {
        integ_pg_conn_t* conn = integ_pg_connect(
            "127.0.0.1", KEEL_PROXY_PORT,
            TEST_USER, TEST_PASSWORD, TEST_DATABASE
        );
        
        TEST_ASSERT_NOT_NULL(conn);
        if (!conn) continue;
        
        /* Execute multiple queries */
        for (int q = 0; q < 10; q++) {
            int64_t result;
            char query[64];
            snprintf(query, sizeof(query), "SELECT %d + %d", round, q);
            
            bool ok = integ_pg_query_int(conn, query, &result);
            TEST_ASSERT(ok);
            TEST_ASSERT_EQ(result, round + q);
        }
        
        integ_pg_close(conn);
        
        /* Small delay to let pool recycle connection */
        usleep(50000);  /* 50ms */
    }
    
    TEST_END();
}

static void test_pool_concurrent_queries(void) {
    TEST_BEGIN("concurrent queries through proxy (tests backend_pool.c, reactor)");
    
    if (g_skip_tests) {
        printf("SKIP\n");
        return;
    }
    
    /* Open connections */
    #define CONCURRENT_CONNS 5
    integ_pg_conn_t* conns[CONCURRENT_CONNS] = {0};
    
    for (int i = 0; i < CONCURRENT_CONNS; i++) {
        conns[i] = integ_pg_connect(
            "127.0.0.1", KEEL_PROXY_PORT,
            TEST_USER, TEST_PASSWORD, TEST_DATABASE
        );
        TEST_ASSERT_NOT_NULL(conns[i]);
    }
    
    /* Execute queries rapidly - this tests the async I/O handling */
    for (int iter = 0; iter < 20; iter++) {
        for (int i = 0; i < CONCURRENT_CONNS; i++) {
            if (!conns[i]) continue;
            
            int64_t result;
            char query[64];
            snprintf(query, sizeof(query), "SELECT %d * %d", iter, i);
            
            bool ok = integ_pg_query_int(conns[i], query, &result);
            TEST_ASSERT(ok);
            TEST_ASSERT_EQ(result, iter * i);
        }
    }
    
    /* Close all */
    for (int i = 0; i < CONCURRENT_CONNS; i++) {
        integ_pg_close(conns[i]);
    }
    
    TEST_END();
}

/* ============================================================================
 * Transaction Tests
 * ============================================================================ */

static void test_proxy_transaction(void) {
    TEST_BEGIN("transaction through proxy");
    
    if (g_skip_tests) {
        printf("SKIP\n");
        return;
    }
    
    integ_pg_conn_t* conn = integ_pg_connect(
        "127.0.0.1", KEEL_PROXY_PORT,
        TEST_USER, TEST_PASSWORD, TEST_DATABASE
    );
    
    TEST_ASSERT_NOT_NULL(conn);
    if (!conn) return;
    
    /* Create temp table */
    bool ok = integ_pg_exec(conn, "CREATE TEMP TABLE test_txn (id int, val text)");
    TEST_ASSERT(ok);
    
    /* Begin transaction */
    ok = integ_pg_exec(conn, "BEGIN");
    TEST_ASSERT(ok);
    
    /* Insert data */
    ok = integ_pg_exec(conn, "INSERT INTO test_txn VALUES (1, 'test')");
    TEST_ASSERT(ok);
    
    /* Commit */
    ok = integ_pg_exec(conn, "COMMIT");
    TEST_ASSERT(ok);
    
    /* Verify data persisted */
    int64_t count;
    ok = integ_pg_query_int(conn, "SELECT COUNT(*) FROM test_txn", &count);
    TEST_ASSERT(ok);
    TEST_ASSERT_EQ(count, 1);
    
    integ_pg_close(conn);
    
    TEST_END();
}

static void test_proxy_rollback(void) {
    TEST_BEGIN("rollback through proxy");
    
    if (g_skip_tests) {
        printf("SKIP\n");
        return;
    }
    
    integ_pg_conn_t* conn = integ_pg_connect(
        "127.0.0.1", KEEL_PROXY_PORT,
        TEST_USER, TEST_PASSWORD, TEST_DATABASE
    );
    
    TEST_ASSERT_NOT_NULL(conn);
    if (!conn) return;
    
    /* Create temp table */
    bool ok = integ_pg_exec(conn, "CREATE TEMP TABLE test_rb (id int)");
    TEST_ASSERT(ok);
    
    /* Insert baseline data */
    ok = integ_pg_exec(conn, "INSERT INTO test_rb VALUES (1)");
    TEST_ASSERT(ok);
    
    /* Begin transaction */
    ok = integ_pg_exec(conn, "BEGIN");
    TEST_ASSERT(ok);
    
    /* Insert more data */
    ok = integ_pg_exec(conn, "INSERT INTO test_rb VALUES (2), (3), (4)");
    TEST_ASSERT(ok);
    
    /* Rollback */
    ok = integ_pg_exec(conn, "ROLLBACK");
    TEST_ASSERT(ok);
    
    /* Verify rollback - should only have 1 row */
    int64_t count;
    ok = integ_pg_query_int(conn, "SELECT COUNT(*) FROM test_rb", &count);
    TEST_ASSERT(ok);
    TEST_ASSERT_EQ(count, 1);
    
    integ_pg_close(conn);
    
    TEST_END();
}

/* ============================================================================
 * Large Data Tests (exercises reactor buffer handling)
 * ============================================================================ */

static void test_proxy_large_result(void) {
    TEST_BEGIN("large result through proxy (tests reactor)");
    
    if (g_skip_tests) {
        printf("SKIP\n");
        return;
    }
    
    integ_pg_conn_t* conn = integ_pg_connect(
        "127.0.0.1", KEEL_PROXY_PORT,
        TEST_USER, TEST_PASSWORD, TEST_DATABASE
    );
    
    TEST_ASSERT_NOT_NULL(conn);
    if (!conn) return;
    
    /* Generate many rows - exercises async I/O buffer handling */
    int64_t count;
    bool ok = integ_pg_query_int(conn, 
        "SELECT COUNT(*) FROM generate_series(1, 10000)", &count);
    TEST_ASSERT(ok);
    TEST_ASSERT_EQ(count, 10000);
    
    integ_pg_close(conn);
    
    TEST_END();
}

static void test_proxy_large_query(void) {
    TEST_BEGIN("large query through proxy");
    
    if (g_skip_tests) {
        printf("SKIP\n");
        return;
    }
    
    integ_pg_conn_t* conn = integ_pg_connect(
        "127.0.0.1", KEEL_PROXY_PORT,
        TEST_USER, TEST_PASSWORD, TEST_DATABASE
    );
    
    TEST_ASSERT_NOT_NULL(conn);
    if (!conn) return;
    
    /* Build a large query string */
    char* large_query = malloc(64 * 1024);
    TEST_ASSERT_NOT_NULL(large_query);
    if (!large_query) return;
    
    strcpy(large_query, "SELECT ");
    for (int i = 0; i < 1000; i++) {
        char part[64];
        snprintf(part, sizeof(part), "%d + ", i);
        strcat(large_query, part);
    }
    strcat(large_query, "0");
    
    int64_t result;
    bool ok = integ_pg_query_int(conn, large_query, &result);
    TEST_ASSERT(ok);
    
    /* Sum of 0..999 = 999*1000/2 = 499500 */
    TEST_ASSERT_EQ(result, 499500);
    
    free(large_query);
    integ_pg_close(conn);
    
    TEST_END();
}

/* ============================================================================
 * Stress Tests (exercises worker.c, session.c)
 * ============================================================================ */

static void test_proxy_rapid_connect_disconnect(void) {
    TEST_BEGIN("rapid connect/disconnect (tests worker.c, session.c)");
    
    if (g_skip_tests) {
        printf("SKIP\n");
        return;
    }
    
    /* Rapidly connect and disconnect to stress the worker threads */
    for (int i = 0; i < 20; i++) {
        integ_pg_conn_t* conn = integ_pg_connect(
            "127.0.0.1", KEEL_PROXY_PORT,
            TEST_USER, TEST_PASSWORD, TEST_DATABASE
        );
        
        TEST_ASSERT_NOT_NULL(conn);
        if (conn) {
            /* Quick query */
            int64_t result;
            bool ok = integ_pg_query_int(conn, "SELECT 1", &result);
            TEST_ASSERT(ok);
            integ_pg_close(conn);
        }
    }
    
    TEST_END();
}

static void test_proxy_many_queries_single_conn(void) {
    TEST_BEGIN("many queries on single connection");
    
    if (g_skip_tests) {
        printf("SKIP\n");
        return;
    }
    
    integ_pg_conn_t* conn = integ_pg_connect(
        "127.0.0.1", KEEL_PROXY_PORT,
        TEST_USER, TEST_PASSWORD, TEST_DATABASE
    );
    
    TEST_ASSERT_NOT_NULL(conn);
    if (!conn) return;
    
    /* Execute many queries on same connection */
    for (int i = 0; i < 100; i++) {
        int64_t result;
        char query[64];
        snprintf(query, sizeof(query), "SELECT %d", i);
        
        bool ok = integ_pg_query_int(conn, query, &result);
        TEST_ASSERT(ok);
        TEST_ASSERT_EQ(result, i);
    }
    
    integ_pg_close(conn);
    
    TEST_END();
}

/* ============================================================================
 * Error Handling Tests
 * ============================================================================ */

static void test_proxy_invalid_query(void) {
    TEST_BEGIN("invalid query through proxy");
    
    if (g_skip_tests) {
        printf("SKIP\n");
        return;
    }
    
    integ_pg_conn_t* conn = integ_pg_connect(
        "127.0.0.1", KEEL_PROXY_PORT,
        TEST_USER, TEST_PASSWORD, TEST_DATABASE
    );
    
    TEST_ASSERT_NOT_NULL(conn);
    if (!conn) return;
    
    /* Invalid SQL should fail but not crash proxy */
    bool ok = integ_pg_exec(conn, "SELEKT 1");
    TEST_ASSERT(!ok);  /* Should fail */
    
    /* Connection should still work */
    int64_t result;
    ok = integ_pg_query_int(conn, "SELECT 1", &result);
    TEST_ASSERT(ok);
    TEST_ASSERT_EQ(result, 1);
    
    integ_pg_close(conn);
    
    TEST_END();
}

static void test_proxy_nonexistent_table(void) {
    TEST_BEGIN("query nonexistent table through proxy");
    
    if (g_skip_tests) {
        printf("SKIP\n");
        return;
    }
    
    integ_pg_conn_t* conn = integ_pg_connect(
        "127.0.0.1", KEEL_PROXY_PORT,
        TEST_USER, TEST_PASSWORD, TEST_DATABASE
    );
    
    TEST_ASSERT_NOT_NULL(conn);
    if (!conn) return;
    
    /* Query nonexistent table */
    bool ok = integ_pg_exec(conn, "SELECT * FROM nonexistent_table_xyz");
    TEST_ASSERT(!ok);  /* Should fail */
    
    /* Connection should still work */
    int64_t result;
    ok = integ_pg_query_int(conn, "SELECT 42", &result);
    TEST_ASSERT(ok);
    TEST_ASSERT_EQ(result, 42);
    
    integ_pg_close(conn);
    
    TEST_END();
}

/* ============================================================================
 * DDL Tests
 * ============================================================================ */

static void test_proxy_create_table(void) {
    TEST_BEGIN("create/drop table through proxy");
    
    if (g_skip_tests) {
        printf("SKIP\n");
        return;
    }
    
    integ_pg_conn_t* conn = integ_pg_connect(
        "127.0.0.1", KEEL_PROXY_PORT,
        TEST_USER, TEST_PASSWORD, TEST_DATABASE
    );
    
    TEST_ASSERT_NOT_NULL(conn);
    if (!conn) return;
    
    /* Drop if exists */
    integ_pg_exec(conn, "DROP TABLE IF EXISTS test_proxy_table");
    
    /* Create table */
    bool ok = integ_pg_exec(conn, 
        "CREATE TABLE test_proxy_table (id serial PRIMARY KEY, name text)");
    TEST_ASSERT(ok);
    
    /* Insert data */
    ok = integ_pg_exec(conn, 
        "INSERT INTO test_proxy_table (name) VALUES ('test1'), ('test2')");
    TEST_ASSERT(ok);
    
    /* Query count */
    int64_t count;
    ok = integ_pg_query_int(conn, "SELECT COUNT(*) FROM test_proxy_table", &count);
    TEST_ASSERT(ok);
    TEST_ASSERT_EQ(count, 2);
    
    /* Drop table */
    ok = integ_pg_exec(conn, "DROP TABLE test_proxy_table");
    TEST_ASSERT(ok);
    
    integ_pg_close(conn);
    
    TEST_END();
}

/* ============================================================================
 * Main Test Runner
 * ============================================================================ */

int main(void) {
    printf("=== KEEL Proxy End-to-End Integration Tests ===\n\n");
    printf("These tests start the KEEL proxy and connect THROUGH it.\n");
    printf("This exercises: backend_pool.c, reactor, worker.c, session.c, engine_flow.c\n\n");
    
    setup();
    
    if (g_skip_tests) {
        printf("\nNo tests run - see above for reason\n");
        return 0;
    }
    
    printf("\n--- Basic Connection Tests ---\n");
    test_proxy_connect();
    test_proxy_simple_query();
    test_proxy_string_query();
    
    printf("\n--- Connection Pooling Tests ---\n");
    test_pool_multiple_connections();
    test_pool_connection_reuse();
    test_pool_concurrent_queries();
    
    printf("\n--- Transaction Tests ---\n");
    test_proxy_transaction();
    test_proxy_rollback();
    
    printf("\n--- Large Data Tests ---\n");
    test_proxy_large_result();
    test_proxy_large_query();
    
    printf("\n--- Stress Tests ---\n");
    test_proxy_rapid_connect_disconnect();
    test_proxy_many_queries_single_conn();
    
    printf("\n--- Error Handling Tests ---\n");
    test_proxy_invalid_query();
    test_proxy_nonexistent_table();
    
    printf("\n--- DDL Tests ---\n");
    test_proxy_create_table();
    
    teardown();
    
    printf("\n");
    return test_summary();
}
