/**
 * @file scatter_2pc.h
 * @brief Two-phase commit coordinator for scatter (multi-shard) write transactions.
 * @author Charly Batista
 * @copyright Copyright (c) Virtlabs, https://virtlabs.io
 * @license GNU Affero General Public License v3.0
 *
 * When a write query is scattered to N shards, each shard begins an independent
 * transaction.  A network partition or shard failure after some shards have
 * committed but before others can leave the database in an inconsistent state.
 *
 * The SQL standard defines a two-phase commit protocol that most databases
 * implement with database-specific syntax:
 *   PostgreSQL: PREPARE TRANSACTION 'gid', COMMIT PREPARED 'gid',
 *               ROLLBACK PREPARED 'gid'
 *   MySQL/XA:   XA PREPARE 'gid', XA COMMIT 'gid', XA ROLLBACK 'gid'
 *
 * This coordinator manages GIDs and participant state; the SQL text for each
 * phase is generated by the caller (protocol layer) using the GID from
 * keel_2pc_coord_gid().
 *   1. Generates a unique GID per shard per transaction.
 *   2. Tracks per-shard preparation state.
 *   3. Provides query text helpers for PREPARE/COMMIT/ROLLBACK PREPARED.
 *   4. Enforces the state machine so the proxy cannot issue phase-2 before
 *      all participants have completed phase-1 (unless rolling back).
 *
 * Usage
 * -----
 * @code
 *   keel_2pc_coord_t coord;
 *   keel_2pc_coord_init(&coord, session_id, seq);
 *   keel_2pc_coord_begin(&coord, &scatter_plan);
 *
 *   // Phase 1: send PREPARE TRANSACTION '<gid>' to each shard
 *   for (size_t i = 0; i < coord.count; i++) {
 *       const char* gid = keel_2pc_coord_gid(&coord, coord.participants[i].shard_index);
 *       // exec_on_shard(i, "PREPARE TRANSACTION '%s'", gid);
 *       keel_2pc_coord_prepare(&coord, coord.participants[i].shard_index);
 *   }
 *
 *   if (keel_2pc_coord_all_prepared(&coord)) {
 *       keel_2pc_coord_commit_all(&coord);   // Phase 2 — commit
 *   } else {
 *       keel_2pc_coord_rollback_all(&coord); // Phase 2 — abort
 *   }
 * @endcode
 *
 * Thread safety: None. External synchronisation required if shared.
 */

#ifndef KEEL_SCATTER_2PC_H
#define KEEL_SCATTER_2PC_H

#include "keel_types.h"
#include "keel_error.h"
#include "keel/core/router.h"   /* keel_scatter_plan_t, KEEL_SCATTER_MAX_SHARDS */

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ============================================================================
 * Constants
 * ============================================================================ */

/** Maximum participants (one per shard). */
#define KEEL_2PC_MAX_PARTICIPANTS KEEL_SCATTER_MAX_SHARDS

/**
 * @brief Maximum length of a GID string (including NUL terminator).
 *
 * Format: "keel_<session_id>_<seq>_s<shard_index>"
 * e.g.  "keel_18446744073709551615_18446744073709551615_s63" — 52 chars + NUL.
 * We round up to 64 for alignment.
 */
#define KEEL_2PC_GID_MAX 64

/* ============================================================================
 * Types
 * ============================================================================ */

/**
 * @brief Per-participant (per-shard) state in the 2PC protocol.
 */
typedef enum keel_2pc_state {
    KEEL_2PC_IDLE = 0,     /**< Not yet started */
    KEEL_2PC_ACTIVE,       /**< Transaction in flight (before PREPARE) */
    KEEL_2PC_PREPARED,     /**< PREPARE TRANSACTION acknowledged */
    KEEL_2PC_COMMITTED,    /**< COMMIT PREPARED acknowledged */
    KEEL_2PC_ROLLED_BACK,  /**< ROLLBACK PREPARED acknowledged */
    KEEL_2PC_ABORTED,      /**< PREPARE failed; shard must be rolled back normally */
} keel_2pc_state_t;

/**
 * @brief State record for one shard participant.
 */
typedef struct keel_2pc_participant {
    size_t           shard_index;          /**< Logical shard index */
    char             gid[KEEL_2PC_GID_MAX]; /**< Globally-unique transaction ID */
    keel_2pc_state_t state;                /**< Current protocol state */
} keel_2pc_participant_t;

/**
 * @brief Two-phase commit coordinator.
 *
 * Embed or stack-allocate; initialise with keel_2pc_coord_init().
 */
typedef struct keel_2pc_coord {
    char                   gid_prefix[40]; /**< Shared GID prefix for this tx */
    keel_2pc_participant_t participants[KEEL_2PC_MAX_PARTICIPANTS];
    size_t                 count;          /**< Number of active participants */
    keel_2pc_state_t       state;          /**< Overall coordinator state */
} keel_2pc_coord_t;

/* ============================================================================
 * Lifecycle
 * ============================================================================ */

/**
 * @brief Initialise a coordinator for a new transaction.
 *
 * Sets a GID prefix of the form "keel_<session_id>_<seq>" that is unique
 * across sessions and re-used prepare sequences within a session.
 *
 * @param coord      Coordinator to initialise (written to zero first).
 * @param session_id Opaque per-session identifier (e.g. connection handle id).
 * @param seq        Monotonically increasing sequence number within the session.
 */
void keel_2pc_coord_init(keel_2pc_coord_t* coord,
                         uint64_t          session_id,
                         uint64_t          seq);

/**
 * @brief Reset a coordinator for reuse without re-initialising the prefix.
 *
 * Clears participant state but preserves @c gid_prefix so that a new sequence
 * number can be injected via @ref keel_2pc_coord_init before the next
 * transaction.
 */
void keel_2pc_coord_reset(keel_2pc_coord_t* coord);

/* ============================================================================
 * Protocol phases
 * ============================================================================ */

/**
 * @brief Record all participating shards from a completed scatter plan.
 *
 * Iterates bits in @p plan->participating_shards_mask and creates one
 * participant entry per shard.  Each participant is assigned a unique GID
 * derived from the coordinator prefix and its shard index.
 *
 * May only be called when @c coord->state == @ref KEEL_2PC_IDLE.
 *
 * @return KEEL_OK on success.
 *         KEEL_ERR_INVALID_ARG if coord or plan is NULL, or state is not IDLE.
 *         KEEL_ERR_OVERFLOW if the mask contains more than
 *                           KEEL_2PC_MAX_PARTICIPANTS set bits.
 */
keel_error_t keel_2pc_coord_begin(keel_2pc_coord_t*          coord,
                                   const keel_scatter_plan_t* plan);

/**
 * @brief Mark a shard as having successfully prepared (phase 1 complete).
 *
 * Call this after the PREPARE TRANSACTION command has been acknowledged by
 * the backend for @p shard_idx.  The participant state transitions from
 * @ref KEEL_2PC_ACTIVE → @ref KEEL_2PC_PREPARED.
 *
 * @return KEEL_OK on success.
 *         KEEL_ERR_NOT_FOUND if no participant with @p shard_idx exists.
 *         KEEL_ERR_INVALID_ARG if the participant is not in ACTIVE state.
 */
keel_error_t keel_2pc_coord_prepare(keel_2pc_coord_t* coord, size_t shard_idx);

/**
 * @brief Mark a shard as having aborted preparation (PREPARE failed).
 *
 * Transitions ACTIVE → ABORTED.  After calling this, the shard should be
 * rolled back using a normal ROLLBACK (not ROLLBACK PREPARED).
 *
 * @return KEEL_OK on success.
 *         KEEL_ERR_NOT_FOUND if no participant with @p shard_idx exists.
 *         KEEL_ERR_INVALID_ARG if the participant is not in ACTIVE state.
 */
keel_error_t keel_2pc_coord_prepare_failed(keel_2pc_coord_t* coord, size_t shard_idx);

/**
 * @brief Commit all PREPARED participants (phase 2 — commit path).
 *
 * All participants must be in @ref KEEL_2PC_PREPARED state.
 * Transitions each to @ref KEEL_2PC_COMMITTED and sets the overall state.
 *
 * @return KEEL_OK on success.
 *         KEEL_ERR_INVALID_ARG if any participant is not in PREPARED state.
 */
keel_error_t keel_2pc_coord_commit_all(keel_2pc_coord_t* coord);

/**
 * @brief Roll back all PREPARED (and ACTIVE) participants (phase 2 — abort path).
 *
 * PREPARED participants → ROLLED_BACK (requires ROLLBACK PREPARED).
 * ACTIVE participants   → ROLLED_BACK (requires normal ROLLBACK).
 * ABORTED participants  are left unchanged (already rolled back).
 *
 * @return KEEL_OK — always succeeds (tolerant of mixed states for abort).
 */
keel_error_t keel_2pc_coord_rollback_all(keel_2pc_coord_t* coord);

/* ============================================================================
 * Inspection
 * ============================================================================ */

/**
 * @brief Return the GID assigned to @p shard_idx, or NULL if not found.
 */
const char* keel_2pc_coord_gid(const keel_2pc_coord_t* coord, size_t shard_idx);

/**
 * @brief Return the protocol state for @p shard_idx.
 *
 * Returns @ref KEEL_2PC_IDLE when no participant with that index exists.
 */
keel_2pc_state_t keel_2pc_coord_shard_state(const keel_2pc_coord_t* coord,
                                              size_t shard_idx);

/**
 * @brief Return true if every participant has reached @ref KEEL_2PC_PREPARED.
 *
 * A coordinator with zero participants returns false.
 */
bool keel_2pc_coord_all_prepared(const keel_2pc_coord_t* coord);

/**
 * @brief Return the overall coordinator state.
 */
static inline keel_2pc_state_t keel_2pc_coord_overall_state(const keel_2pc_coord_t* coord)
{
    return coord ? coord->state : KEEL_2PC_IDLE;
}

/**
 * @brief Return the number of participants registered with this coordinator.
 */
static inline size_t keel_2pc_coord_participant_count(const keel_2pc_coord_t* coord)
{
    return coord ? coord->count : 0;
}

#ifdef __cplusplus
}
#endif

#endif /* KEEL_SCATTER_2PC_H */
