#!/usr/bin/env bash
# ============================================================================
# hardening-slow-client-fast-server.sh — Backpressure resilience test
# ============================================================================
#
# Tests that the KEEL proxy survives when a client reads data much slower
# than the backend produces it.  This is a classic backpressure scenario:
# a large COPY TO STDOUT result set is generated by the server, but the
# client-side pipe is throttled to CLIENT_BPS bytes per second via a
# Python rate-limiter.
#
# Why this matters:
#   If the proxy does not handle backpressure correctly, it will either:
#   - Accumulate unbounded memory buffering the fast server's output
#   - Deadlock when internal buffers fill and the io_uring ring stalls
#   - Crash with an OOM or assertion failure
#   A correct proxy applies flow control: it stops reading from the backend
#   when the client-side socket buffer is full, and resumes when drained.
#
# Algorithm:
#   1. Use psql to execute a COPY (SELECT generate_series ...) TO STDOUT
#      query that produces TOTAL_ROWS × ROW_BYTES of output.
#   2. Pipe psql output through a Python script that reads at most
#      CLIENT_BPS bytes per second (rate-limited via time.sleep).
#   3. Check PIPESTATUS for both psql and python exit codes.
#   4. PASS if the proxy handled the slow drain without crashing.
#
# Environment Variables:
#   PROXY_HOST    Proxy address (default: 127.0.0.1)
#   PROXY_PORT    Proxy port (default: 7432)
#   DB_USER       Database user (default: postgres)
#   DB_PASSWORD   Database password (default: postgres)
#   DB_NAME       Database name (default: testdb)
#   TOTAL_ROWS    Number of rows to generate (default: 10000)
#   ROW_BYTES     Approximate bytes per row via lpad() (default: 2048)
#   CLIENT_BPS    Client read rate in bytes/second (default: 102400 = 100 KB/s)
#
# Prerequisites:
#   - psql and python3 on PATH
#   - KEEL proxy running on PROXY_HOST:PROXY_PORT
#
# Exit Codes:
#   0  PASS — proxy survived backpressure
#   1  FAIL — proxy crashed or connection aborted
#
# Usage:
#   ./scripts/hardening-slow-client-fast-server.sh
#   TOTAL_ROWS=1000 CLIENT_BPS=51200 ./scripts/hardening-slow-client-fast-server.sh
# ============================================================================
set -euo pipefail

PROXY_HOST="${PROXY_HOST:-127.0.0.1}"
PROXY_PORT="${PROXY_PORT:-7432}"
DB_USER="${DB_USER:-postgres}"
DB_PASSWORD="${DB_PASSWORD:-postgres}"
DB_NAME="${DB_NAME:-testdb}"

TOTAL_ROWS="${TOTAL_ROWS:-100000}"
ROW_BYTES="${ROW_BYTES:-1024}"
CLIENT_BPS="${CLIENT_BPS:-10240}"

echo "[slow-client] requesting large result through proxy"
echo "[slow-client] throttling client read rate to ${CLIENT_BPS} B/s"

set +e
PGPASSWORD="$DB_PASSWORD" psql \
  -h "$PROXY_HOST" -p "$PROXY_PORT" -U "$DB_USER" -d "$DB_NAME" \
  -X -A -t \
  -c "COPY (SELECT repeat('x', ${ROW_BYTES}) FROM generate_series(1, ${TOTAL_ROWS})) TO STDOUT" \
| python3 - "$CLIENT_BPS" <<'PY'
import sys, time
bps = max(int(sys.argv[1]), 1)
chunk = 1024
sleep_s = chunk / float(bps)
stream = sys.stdin.buffer
while True:
    data = stream.read(chunk)
    if not data:
        break
    time.sleep(sleep_s)
print("[slow-client] completed throttled receive", file=sys.stderr)
PY
pipe_status=("${PIPESTATUS[@]}")
psql_rc=${pipe_status[0]:-0}
py_rc=${pipe_status[1]:-0}
set -e

if [[ "$py_rc" -ne 0 ]]; then
  echo "[slow-client] FAIL: throttled consumer exited with rc=$py_rc" >&2
  exit "$py_rc"
fi

if [[ "$psql_rc" -ne 0 && "$psql_rc" -ne 141 ]]; then
  echo "[slow-client] FAIL: psql exited with rc=$psql_rc" >&2
  exit "$psql_rc"
fi

echo "[slow-client] PASS: transfer completed without crash"
