/**
 * @file web_ui.c
 * @brief Embedded single-page application HTML for the web management UI.
 *
 * Separated from admin.c so tests can link keel_web_ui without dragging in
 * the full engine, stats collector, or TLS subsystems.
 */

#include "keel/core/web_ui.h"

/*
 * Self-contained SPA: dark-themed dashboard that polls /api/status.json every
 * five seconds and renders engine state, session counts, pool utilisation,
 * query throughput, and error rates.  No external dependencies are loaded —
 * the page is fully usable without internet access.
 */
const char keel_ui_html[] =
    "<!DOCTYPE html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "<meta charset=\"UTF-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\n"
    "<title>Keel \xe2\x80\x94 Status</title>\n"
    "<style>\n"
    "*{box-sizing:border-box;margin:0;padding:0}\n"
    "body{font-family:system-ui,sans-serif;background:#0f1117;color:#c9d1d9;"
         "min-height:100vh;padding:1.5rem 2rem}\n"
    "a{color:#58a6ff;text-decoration:none}\n"
    "a:hover{text-decoration:underline}\n"
    "h1{font-size:1.5rem;font-weight:700;letter-spacing:-.5px}\n"
    ".sub{font-size:.82rem;color:#6e7681;margin-top:.2rem}\n"
    ".hdr{display:flex;align-items:flex-start;gap:1.2rem;margin-bottom:1.8rem;flex-wrap:wrap}\n"
    ".hdr-right{margin-left:auto;text-align:right}\n"
    "#ts{font-size:.75rem;color:#6e7681}\n"
    ".badge{display:inline-block;padding:.2rem .65rem;border-radius:9999px;"
           "font-size:.72rem;font-weight:600;text-transform:uppercase;letter-spacing:.5px;"
           "vertical-align:middle;margin-top:.3rem}\n"
    ".badge-active{background:#1a4731;color:#3fb950}\n"
    ".badge-other{background:#3d1a1a;color:#f85149}\n"
    ".badge-unknown{background:#21262d;color:#8b949e}\n"
    ".grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));"
          "gap:1rem;margin-bottom:2rem}\n"
    ".card{background:#161b22;border:1px solid #21262d;border-radius:8px;padding:1rem 1.1rem}\n"
    ".card h2{font-size:.7rem;color:#8b949e;text-transform:uppercase;letter-spacing:.5px;"
             "margin-bottom:.55rem}\n"
    ".metric{font-size:1.55rem;font-weight:600;color:#e6edf3;"
            "font-variant-numeric:tabular-nums}\n"
    ".detail{font-size:.75rem;color:#6e7681;margin-top:.3rem;line-height:1.5}\n"
    ".links{font-size:.82rem;color:#6e7681;margin-top:2rem;border-top:1px solid #21262d;"
           "padding-top:1rem}\n"
    ".links a{margin-right:1.2rem}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<div class='hdr'>\n"
    "  <div>\n"
    "    <h1>&#x2665;&nbsp;Keel</h1>\n"
    "    <div class='sub'>Connection proxy &mdash; Management UI</div>\n"
    "  </div>\n"
    "  <div class='hdr-right'>\n"
    "    <span id='badge' class='badge badge-unknown'>&#x25cf; unknown</span>\n"
    "    <div id='ts' class='sub'>&nbsp;</div>\n"
    "  </div>\n"
    "</div>\n"
    "<div class='grid'>\n"
    "  <div class='card'><h2>Workers</h2>"
         "<div class='metric' id='m-workers'>-</div></div>\n"
    "  <div class='card'><h2>Uptime</h2>"
         "<div class='metric' id='m-uptime'>-</div></div>\n"
    "  <div class='card'><h2>Active Sessions</h2>"
         "<div class='metric' id='m-sess-active'>-</div>"
         "<div class='detail' id='d-sess'></div></div>\n"
    "  <div class='card'><h2>Pool Active / Idle</h2>"
         "<div class='metric' id='m-pool'>-</div>"
         "<div class='detail' id='d-pool'></div></div>\n"
    "  <div class='card'><h2>Queries</h2>"
         "<div class='metric' id='m-queries'>-</div>"
         "<div class='detail' id='d-queries'></div></div>\n"
    "  <div class='card'><h2>Errors</h2>"
         "<div class='metric' id='m-errors'>-</div>"
         "<div class='detail' id='d-errors'></div></div>\n"
    "</div>\n"
    "<div class='links'>\n"
    "  <a href='/metrics'>Prometheus metrics</a>\n"
    "  <a href='/api/status.json'>JSON status</a>\n"
    "  <a href='/healthz'>healthz</a>\n"
    "  <a href='/readyz'>readyz</a>\n"
    "  <a href='/livez'>livez</a>\n"
    "</div>\n"
    "<script>\n"
    "function fmt(n){\n"
    "  if(n===undefined||n===null)return'-';\n"
    "  if(n>=1e9)return(n/1e9).toFixed(2)+'B';\n"
    "  if(n>=1e6)return(n/1e6).toFixed(2)+'M';\n"
    "  if(n>=1e3)return(n/1e3).toFixed(1)+'K';\n"
    "  return String(n);\n"
    "}\n"
    "function fmtUp(s){\n"
    "  var h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sc=Math.floor(s%60);\n"
    "  if(h>0)return h+'h '+m+'m';\n"
    "  if(m>0)return m+'m '+sc+'s';\n"
    "  return sc+'s';\n"
    "}\n"
    "function set(id,v){var e=document.getElementById(id);if(e)e.textContent=v;}\n"
    "function refresh(){\n"
    "  fetch('/api/status.json')\n"
    "    .then(function(r){return r.json();})\n"
    "    .then(function(d){\n"
    "      var st=d.state||'unknown';\n"
    "      var b=document.getElementById('badge');\n"
    "      b.textContent='\\u25cf '+st;\n"
    "      b.className='badge '+(st==='active'?'badge-active':\n"
    "                            st==='stopped'?'badge-other':'badge-other');\n"
    "      set('m-workers',fmt(d.workers));\n"
    "      set('m-uptime',fmtUp(d.uptime_seconds||0));\n"
    "      var s=d.sessions||{};\n"
    "      set('m-sess-active',fmt(s.active));\n"
    "      set('d-sess','created: '+fmt(s.created)+' \\u00b7 closed: '+fmt(s.closed));\n"
    "      var p=d.pool||{};\n"
    "      set('m-pool',(p.active||0)+' / '+(p.idle||0));\n"
    "      set('d-pool','total: '+fmt(p.total)+' \\u00b7 waiting: '+fmt(p.waiting));\n"
    "      var q=d.queries||{};\n"
    "      set('m-queries',fmt(q.total));\n"
    "      set('d-queries','R: '+fmt(q.read)+' \\u00b7 W: '+fmt(q.write)\n"
    "                      +' \\u00b7 TX: '+fmt(q.tx));\n"
    "      var e=d.errors||{};\n"
    "      set('m-errors',fmt(e.total));\n"
    "      set('d-errors','auth: '+fmt(e.auth)+' \\u00b7 timeout: '+fmt(e.timeout));\n"
    "      set('ts','Updated '+new Date().toLocaleTimeString());\n"
    "    })\n"
    "    .catch(function(){set('ts','Reconnecting...');});\n"
    "}\n"
    "refresh();\n"
    "setInterval(refresh,5000);\n"
    "</script>\n"
    "</body></html>\n";
